// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGrO_p3RSTcdgFzdzqc3Muuus0kIif7k',
    appId: '1:785019622876:web:d92f5323605159a0bc6b19',
    messagingSenderId: '785019622876',
    projectId: 'zenith-08',
    authDomain: 'zenith-08.firebaseapp.com',
    databaseURL:
        "https://zenith-08-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'zenith-08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYl-radxtBQ5DZawOuQhyJsb6rOs1I8yU',
    appId: '1:785019622876:android:ddd33de79cfd8aebbc6b19',
    messagingSenderId: '785019622876',
    projectId: 'zenith-08',
    databaseURL:
        "https://zenith-08-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'zenith-08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmHvIy4bgNA_91F3AyA15RK0Mh6XZv4Jc',
    appId: '1:785019622876:ios:b848f09a238e6aa0bc6b19',
    messagingSenderId: '785019622876',
    projectId: 'zenith-08',
    databaseURL:
        "https://zenith-08-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'zenith-08.appspot.com',
    iosBundleId: 'com.example.zenith',
  );
}
